### ISSUE TITLE
How to build from source code

### ISSUE THREAD

**Issue by SergioGeeK7** [Algorithmus/clevo-audio-mode#1]
Hi. I'm trying to use your code and make some tweaks to work on my laptop. I'm using the command.

g++ -std=gnu++11  main.cpp

some help?
thanks
ps: I'm kind of new to c++

**Comment by SergioGeeK7** [comment]
I just need to read data from pulse audio, I have a macbook pro

**Comment by Algorithmus** [comment]
I have updated the instructions, but it shouldn't be too complicated.

Are you on Linux? Pulseaudio, so far as I know only exists on Linux.

**Comment by SergioGeeK7** [comment]
Thank you, yes. I have Linux. I'll follow up the steps. Thank you
